BrandShop.WebUI/Areas/Administration/Controllers/NewsController.cs
using System.Web.Mvc;
using BrandShop.Domain.EntitiesDb;
using BrandShop.Domain.Interfaces;

namespace BrandShop.WebUI.Areas.Administration.Controllers
{
    [Authorize]
    public class NewsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public NewsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult ShowAll()
        {
            return PartialView(_unitOfWork.NewsRepository.GetAll);
        }

        public ViewResult Create()
        {
            return View(new News());
        }

        [HttpPost]
        public ActionResult Create(News news)
        {
            if (!ModelState.IsValid) return View(news);

            _unitOfWork.NewsRepository.Create(news);

            _unitOfWork.Save();

            TempData["message"] = $"Новость \u2033{news.Header}\u2033 добавлена!";

            return RedirectToAction("Index");
        }

        public ViewResult Edit(int newsId)
        {
            var news = _unitOfWork.NewsRepository.Get(newsId);
            return View(news);
        }

        [HttpPost]
        public ActionResult Edit(News news)
        {
            if (!ModelState.IsValid) return View(news);

            _unitOfWork.NewsRepository.Update(news);

            _unitOfWork.Save();

            TempData["message"] = $"Новость \u2033{news.Header}\u2033 сохранена!";

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int newsId)
        {
            var deletenews = _unitOfWork.NewsRepository.Delete(newsId);
            if (deletenews != null)
            {
                TempData["message"] = $"Новость \u2033{deletenews.Header}\u2033 была удалена";
                _unitOfWork.Save();
            }
            return RedirectToAction("Index");
        }
    }
}

BrandShop.WebUI/Controllers/ProductController.cs
using System.Linq;
using System.Web.Mvc;
using BrandShop.Domain.Entities;
using BrandShop.Domain.Interfaces;
using BrandShop.WebUI.HtmlHelpers;
using BrandShop.WebUI.Models;

namespace BrandShop.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public int PageSize = 12;

        public ProductController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        private void SortProducts(ProductsListViewModel model, OrderFilter filter)
        {
            var prFilter = model.Products.ToList();

            switch (filter)
            {
                case OrderFilter.FirstNew:
                    {
                        prFilter.Reverse();
                        break;
                    }
                case OrderFilter.FirstCheap:
                    {
                        prFilter.Sort((x, y) => x.Price.CompareTo(y.Price));
                        break;
                    }
                case OrderFilter.FirstPricey:
                    {
                        prFilter.Sort((x, y) => x.Price.CompareTo(y.Price));
                        prFilter.Reverse();
                        break;
                    }
            }

            model.Products = prFilter;
        }

        public ViewResult List(string category, OrderFilter filter = OrderFilter.FirstNew, int page = 1)
        {
            var model = new ProductsListViewModel
            {
                Products = _unitOfWork.ProductRepository.GetAll
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(product => product.ProductId),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? _unitOfWork.ProductRepository.GetAll.Count()
                        : _unitOfWork.ProductRepository.GetAll.Count(product => product.Category == category)
                },
                CurrentCategory = category
            };

            SortProducts(model, filter);

            model.Products = model.Products.Skip((page - 1) * PageSize).Take(PageSize);
            model.Filter = filter;

            return View(model);
        }

        [HttpPost]
        public ActionResult List(string category, int filter)
        {
            return RedirectToAction("List", new { category, filter });
        }

        public ViewResult View(int productId, bool sizeError = false)
        {
            if (sizeError) ModelState.AddModelError("Size", "Пожалуйста выберите нужный размер!");

            var model = _unitOfWork.ProductRepository.GetAll.FirstOrDefault(x => x.ProductId == productId);

            ViewBag.SizeArray = model?.Sizes?.Replace(" ", "").Split(',');

            return View(model);
        }

        public FileContentResult GetImage(int imageId, bool isPreview = false)
        {
            var iamge = _unitOfWork.ProductImageRepository.Get(imageId);

            if (iamge == null) return null;

            return isPreview ? 
                    File(iamge.PreviewImageData, iamge.PreviewImageMimeType) : 
                    File(ImageMarker.StickMark(iamge.ImageData), iamge.ImageMimeType);
        }
    }
}

BrandShop.WebUI/Areas/Administration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - Панель администрирования</title>

    <!--Подключаем CSS Twitter Bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/AdminStyle.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.css" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Панель администрирования</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="#">Настройки</a></li>
                    <li><a href="#">@User.Identity.Name</a></li>
                    <li><a href="#">Помощь</a></li>
                </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Поиск...">
                </form>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li title="products"><a href="@Url.Action("Index", "Product")">Каталог товаров</a></li>
                    <li title="orders"><a href="#">Заказы</a></li>
                    <li title="news"><a href="@Url.Action("Index", "News")">Новости</a></li>
                    <li title="users"><a href="#">Пользователи</a></li>
                </ul>
                <ul class="nav nav-sidebar">
                    <li><a href="">Помощь</a></li>
                    <li><a href="">О CMS</a></li>
                </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <h1 class="page-header">@ViewBag.SubTitle</h1>
                @RenderBody()
            </div>

        </div>
    </div>

    <!-- Подключаем jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    @*<script src="~/Scripts/jquery-3.1.1.min.js"></script>*@
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <!-- Подключаем JavaScript Twitter Bootstrap -->
    <script src="~/Scripts/bootstrap.min.js"></script>

    <!-- Подключаем JavaScript Sweetalert2 -->
    <script src="https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.js"></script>

    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    <script src="~/Scripts/MyJavaScript.js"></script>


@if (TempData["message"] != null)
    {
        <script>
            swal({
                text: '@TempData["message"]',
                type: 'success',
                timer: 2000,
                confirmButtonText: "Ok!"
            })
        </script>
    }

    @RenderSection("JS", false)

    @if (!string.IsNullOrEmpty(ViewBag.CurrentPage))
    {
        <script type="text/javascript">
        $(function () {
            $("li[title=@ViewBag.CurrentPage]").addClass("active");
        });
        </script>
    }
</body>
</html>