BrandShop.WebUI/Controllers/AdminOrderController.cs
using System.Linq;
using System.Web.Mvc;
using BrandShop.Domain.EntitiesDb;
using BrandShop.Domain.Interfaces;

namespace BrandShop.WebUI.Controllers
{
    [Authorize]
    public class AdminOrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AdminOrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index(OrderStatus status = OrderStatus.New)
        {
            return View(_unitOfWork.OrderRepository.GetWhere(x => x.OrderStatus == status).Reverse());
        }

        public string GetTotallSum(int orderId)
        {
            var order = _unitOfWork.OrderRepository.Get(orderId);

            var sum = order.OrderItems.ToList().Sum(x => x.Quantity*x.Product.Price);

            return sum.ToString("# руб.");
        }

        public string GetActive(string query, string thisStatus)
        {
            if (query.Length == 0 && thisStatus == "New") return "active";
            if (query.Length == 0) return string.Empty;

            return query.Remove(0, 8) == thisStatus ? "active" : string.Empty;
        }

        public ActionResult DeleteOrder(int orderId)
        {
            var deleteOrder = _unitOfWork.OrderRepository.Delete(orderId);
            if (deleteOrder != null)
            {
                TempData["message"] = $"Заказ \"{deleteOrder.OrderId}\" был удален";
                _unitOfWork.Save();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ViewResult View(int orderId)
        {
            var order = _unitOfWork.OrderRepository.Get(orderId);
            return View("View", order);
        }

        [HttpPost]
        public ActionResult View(Order order)
        {
            // TODO Проверить есть ли тут рекурсия
            if (!ModelState.IsValid) return View(order);

            if(order.OrderId == 0)
                _unitOfWork.OrderRepository.Create(order);
            else
                _unitOfWork.OrderRepository.Update(order);

            _unitOfWork.Save();

            TempData["message"] = $"Изменения в заказе \"{order.OrderId}\" были сохранены";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddOrderLine(int orderId, int productId = 0, string size = "", int quantity = 0)
        {
            if(productId == 0 || quantity == 0 || size == "") return RedirectToAction("View", new { orderId });

            var product = _unitOfWork.ProductRepository.Get(productId);

            if(product == null) return RedirectToAction("View", new { orderId });

            var orderLine = new OrderItem
            {
                Product = product,
                Quantity = quantity,
                SizeProduct = size
            };

            var order = _unitOfWork.OrderRepository.Get(orderId);
            order.OrderItems.Add(orderLine);

            _unitOfWork.OrderRepository.Update(order);
            _unitOfWork.Save();

            return RedirectToAction("View", new {orderId});
        }

        public ActionResult DeleteOrderLine(int orderId, int orderItemId)
        {
            _unitOfWork.OrderItemRepository.Delete(orderItemId);
            _unitOfWork.Save();

            return RedirectToAction("View", new { orderId });
        }
    }
}

BrandShop.WebUI/Controllers/CartController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BrandShop.Domain.Entities;
using BrandShop.Domain.EntitiesDb;
using BrandShop.Domain.Interfaces;
using BrandShop.WebUI.Models;

namespace BrandShop.WebUI.Controllers
{
    public class CartController : Controller
    {
        private readonly IOrderProcessor _orderProcessor;

        private readonly IUnitOfWork _unitOfWork;

        public CartController(IOrderProcessor orderProcessor, IUnitOfWork unitOfWork)
        {
            _orderProcessor = orderProcessor;
            _unitOfWork = unitOfWork;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl, string size)
        {
            if (size == "") return RedirectToAction("View", "Product", new { productId, sizeError = true });
            
            var prod = _unitOfWork.ProductRepository.GetAll.FirstOrDefault(product => product.ProductId == productId);

            if (prod != null)
            {
                cart.AddItem(prod, 1, size);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            var prod = _unitOfWork.ProductRepository.Get(productId);

            if (prod != null)
            {
                cart.RemoveLine(prod);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult Remove(Cart cart, int productId, string returnUrl)
        {
            var prod = _unitOfWork.ProductRepository.Get(productId);

            if (prod != null)
            {
                cart.RemoveLine(prod);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (shippingDetails.TypeDelivery == null)
            {
                ModelState.AddModelError("", "Укажите способ доставки товара!");
            }

            if (ModelState.IsValid)
            {
                var order = new Order
                {
                    Address = shippingDetails.Address,
                    FullName = shippingDetails.ToString(),
                    Email = shippingDetails.Email,
                    PhoneNumber = shippingDetails.PhoneNumber,
                    OrderStatus = OrderStatus.New,
                    CreateDateTime = DateTime.Now,
                    TypeDelivery = shippingDetails.TypeDelivery.Value,
                    OrderItems = cart.Lines.ToList()
                };

                _unitOfWork.OrderRepository.Create(order);

                _orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }

            return View(shippingDetails);
        }
    }
}

BrandShop.WebUI/Controllers/InformationController.cs
using System.Linq;
using System.Web.Mvc;
using BrandShop.Domain.Interfaces;
using BrandShop.WebUI.Models;

namespace BrandShop.WebUI.Controllers
{
    public class InformationController : Controller
    {
        private const int AmountProductsOnHomePage = 8;
        private readonly IUnitOfWork _unitOfWork;

        public InformationController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ViewResult Index()
        {
            var products = _unitOfWork.ProductRepository.GetAll
                .Reverse()
                .Take(AmountProductsOnHomePage)
                .ToList();

            var productsForSlider = _unitOfWork.ProductRepository.GetAll.
                Where(x => x.ForMain)
                .Reverse()
                .ToList();

            var model = new IndexViewModel
            {
                Products = products,
                ProductsForSlider = productsForSlider
            };

            return View(model);
        }

        public ViewResult Contacts()
        {
            return View();
        }

        public ViewResult Delivery()
        {
            return View();
        }

        public ViewResult News()
        {
            var model = _unitOfWork.NewsRepository.GetAll.Reverse().ToList();
            return View(model);
        }
    }
}

BrandShop.WebUI/Controllers/NavController.cs
using System.Linq;
using System.Web.Mvc;
using BrandShop.Domain.Interfaces;

namespace BrandShop.WebUI.Controllers
{
    public class NavController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public NavController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            var categories = _unitOfWork.ProductRepository.GetAll
                .Select(product => product.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }

        public string GetCurrent(string[] segments, string name)
       {
           if (segments.Length< 2)
               return null;

           return name.ToLower() != segments[1].ToLower() ? null : "class=current";
       }
}
}

BrandShop.WebUI/Views/Shared/ProductSummary.cshtml
@model BrandShop.Domain.EntitiesDb.Product

<div class="product clearfix">
    <div class="product-image">
        <a href="@Url.Action("View", "Product", new {@Model.ProductId})">
            @if (Model.ProductImages.Count != 0)
            {
                <img src="@Url.Action("GetImage", "Product", new {imageId = Model.ProductImages.FirstOrDefault()?.ProductImageId, area = ""})">
            }
            else
            {
                <img src="~/Content/images/no_photo.png">
            }
        </a>
        @if (Model.IsHit) { <div class="sale-flash">ХИТ</div> }
        <div class="product-overlay">
            <a href="#">Артикул: @Model.ProductId</a>
        </div>
    </div>
    <div class="product-desc">
        <div class="product-title">
            <h3><a href="@Url.Action("View", "Product", new {@Model.ProductId})">@Model.Name</a>
            </h3>
        </div>
        @if (Model.IsSale)
        {
            <div class="product-price"><ins>@Model.Price.ToString("# руб")</ins> <del>@Model.OldPrice.ToString("# руб")</del></div>
        }
        else
        {
            <div class="product-price">@Model.Price.ToString("# руб")</div>
        }
        
    </div>
</div>

BrandShop.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet"/>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <title>Администратирование</title>
</head>
<body>
<div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    <nav role="navigation" class="navbar navbar-inverse">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("Index", "Information")" class="navbar-brand">Главная</a>
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("Index", "AdminOrder")">Заказы</a></li>
                <li><a href="@Url.Action("Index", "Admin")">Каталог</a></li>
                <li><a href="@Url.Action("Index", "AdminNews")">Новости</a></li>
            </ul>
        </div>
    </nav>
    @RenderBody()
</div>

@if (IsSectionDefined("JScripts"))
{
    @RenderSection("JScripts")
}
</body>
</html>

BrandShop.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="XATTAB"/>
    <meta name="Keywords" content="каталог обуви, обувь каталог, обувной магазин, обувь интернет, обувь интернет магазин, обувь, купить обувь, магазин обуви, сайт обуви, сапоги, сапоги зимние, кроссовки, кроссы, кроссовки зимние, кроссовки спортивные, кеды, конверс, конверсы, Converse, тимбы, тимберленд, Timberland, нью беланс, нью баланс, New Balance, NewBalance">
    <meta name="description" content="street-classic - молодежная обувь и аксессуары"> 

    <!-- Favicons
    ============================================= -->
    <link rel="apple-touch-icon" sizes="180x180" href="/Content/images/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/Content/images/favicons/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/Content/images/favicons/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/Content/images/favicons/manifest.json">
    <link rel="mask-icon" href="/Content/images/favicons/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">

    <!-- Stylesheets
    ============================================= -->
    <link href="https://fonts.googleapis.com/css?family=Roboto&subset=cyrillic" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" type="text/css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.2/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/Content/css/bundle.css" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lt IE 9]>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    <!-- Document Title
    ============================================= -->
    <title>@ViewBag.Title | street-classic - молодежная обувь и аксессуары</title>

    <style media="screen">
        .select-style {
            padding: 5px;
            margin: 0;
            border: 1px solid #EEE;
            border-radius: 15px;
            overflow: hidden;
            background: #F5F5F5;
        }

        .select-style select {
            padding: 5px 8px;
            width: 130%;
            border: none;
            box-shadow: none;
            background-color: transparent;
            background-image: none;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
        }

        .select-style select:focus {
            outline: none;
        }

        .product-image > a {
            transition: all .2s ease-in-out;
        }

        .product-image > a:hover {
            transform: scale(1.05);
        }
    </style>

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter40396010 = new Ya.Metrika({ id:40396010, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script>
    <noscript>
        <div><img src="https://mc.yandex.ru/watch/40396010" style="position: absolute; left: -9999px;" alt=""/>
        </div></noscript> 
    <!-- /Yandex.Metrika counter -->

</head>
<body class="stretched no-smooth-scroll">

    <!-- Document Wrapper
    ============================================= -->
    <div id="wrapper" class="clearfix">

        <!-- Header
        ============================================= -->
        <header id="header">

            <div id="header-wrap">

                <div class="container clearfix">

                    <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

                    <!-- Logo
                    ============================================= -->
                    <div id="logo">
                        <a href="@Url.Action("Index", "Information")" class="standard-logo" data-dark-logo="/Content/images/logo.png"><img src="/Content/images/logo.png" alt="Logo"></a>
                        <a href="@Url.Action("Index", "Information")" class="retina-logo" data-dark-logo="/Content/images/logo.png"><img src="/Content/images/logo.png" alt="Logo"></a>
                    </div>
                    <!-- #logo end -->
                    <!-- Primary Navigation
                    ============================================= -->
                    <nav id="primary-menu">

                        @Html.Action("Menu", "Nav")

                        <!-- Top Cart
                        ============================================= -->
                        @Html.Action("Summary", "Cart")
                        <!-- #top-cart end -->

                    </nav>
                    <!-- #primary-menu end -->

                </div>

            </div>

        </header>
        <!-- #header end -->

        @RenderBody()

        <!-- Footer
        ============================================= -->
        <footer id="footer" class="dark">

            <!-- Copyrights
            ============================================= -->
            <div id="copyrights">

                <div class="container clearfix">
                    <div class="col_half">
                        2016 &copy; Street classic
                        <br> Молодежная одежда и аксесуары
                    </div>

                    <div class="col_half col_last tright">
                        <div class="fright clearfix">
                            <a href="https://www.instagram.com/street.classic/" class="social-icon si-small si-borderless">
                                <i class="icon-instagram"></i>
                                <i class="icon-instagram"></i>
                            </a>
                        </div>

                        <div class="clear"></div>

                        <i class="icon-envelope2"></i> info@street-classic.ru <span class="middot">&middot;</span> <i class="icon-phone"></i> +7 (999) 9780011
                    </div>

                </div>

            </div>
            <!-- #copyrights end -->

        </footer>
        <!-- #footer end -->
    </div>
    <!-- #wrapper end -->
    <!-- Go To Top
    ============================================= -->
    <div id="gotoTop" class="icon-angle-up"></div>

    <!-- External JavaScripts
    ============================================= -->
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="~/Content/js/plugins.js"></script>

    <!-- Footer Scripts
    ============================================= -->
<script type="text/javascript" src="~/Content/js/functions.js"></script>

@if (IsSectionDefined("JScripts"))
{
    @RenderSection("JScripts")
}

</body>
</html>